- name: Baja proceso TSOM IServer
  become: yes
  become_method: sudo
  shell: /opt/BMC/TSIMAgent/pw/pronto/bin/stopremotepw
  register: statustsomis

- name: Resultado de la baja del proceso TSO IServer
  debug:
    msg:
       - "{{ statustsomis.stdout }}"
