- name: Vaidar proceso TSOM IServer
  become: yes
  become_method: sudo
  shell: ps -eo args | grep -qi pronto && echo "IServer ACTIVO" || echo "IServer INACTIVO"
  regiter
  
- name: Resultado de la validacion del proceso TSOM IServer
  debug:
    msg:
       - "{{ statusrepo.stdout }}"
