- name: Reiniciar proceso TSO REPO
  become: yes
  become_method: sudo
  shell: nohup /usr/bin/sh /bmc/TSO/REPO/bin/server.sh restart

- name: Reiniciar proceso TSO CDP
  become: yes
  become_method: sudo
  shell: nohup /usr/bin/sh /bmc/TSO/CDP/bin/server.sh restart

- name: Vaidar proceso TSO REPO
  become: yes
  become_method: sudo
  shell: /usr/bin/sh /bmc/TSO/REPO/bin/server.sh status
  register: statusrepo

- name: Validar proceso TSO CDP
  shell: /usr/bin/sh /bmc/TSO/CDP/bin/server.sh status
  register: statuscdp

- name: Resultado del reinicio del proceso TSO REPO
  debug:
    msg:
       - "{{ statusrepo.stdout }}"

- name: Resultado del reinicio del proceso TSO CDP
  debug:
    msg:
       - "{{ statuscdp.stdout }}"
