- name: Baja proceso TSOM IServer
  become: yes
  become_method: sudo
  shell: /opt/BMC/TSIMAgent/pw/pronto/bin/stopremotepw
  
- name: Alta proceso TSOM IServer
  become: yes
  become_method: sudo
  shell: /opt/BMC/TSIMAgent/pw/pronto/bin/startremotepw
  register: statustsomis

- name: Resultado de la reinicio del proceso TSO IServer
  debug:
    msg:
       - "{{ statustsomis.stdout }}"
